# Create Product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 100
}

###
# Get Products
GET http://localhost:8080/products?page=1&limit=10&sort=asc
Authorization: Bearer <token>

###
# Get Product
GET http://localhost:8080/products/9f344248-ca08-48c2-ac09-ef7e0c29a15b

###
# Update Product
PUT http://localhost:8080/products/9f344248-ca08-48c2-ac09-ef7e0c29a15b HTTP/1.1
Content-Type: application/json

{
  "name": "Product 1 Updated",
  "price": 200
}

###
# Delete Product
DELETE http://localhost:8080/products/9f344248-ca08-48c2-ac09-ef7e0c29a15b
